### ISSUE TITLE
Feature request: add option to ignore new collections.

### ISSUE THREAD

**Issue by arthuraltino** [tssgery/pmm-dizquetv#6]
Currently, all the new collections added to the PMM are automatically added to dizqueTV via your script. It would be nice if we could have an option in the config.yml file to ignore new collections.

**Comment by tssgery** [comment]
Sorry for the delay, I missed this request. This seems like a good addition!

I imagine this would work as follows:
- Add a new setting to the configuration file that instructs pmm-dizquetv to sync all collections or only user specified ones
- If the user chooses to sync all collections, the current behavior continues to work
- If the user chooses to specify the collections, they would need to edit the configuration file and specify every collection to sync

**Comment by tssgery** [comment]
I'd added this ability, in https://github.com/tssgery/pmm-dizquetv/pull/8

After some more thorough testing, it will merge to main

**Comment by tssgery** [comment]
Merged. Changes available in release 0.9.0 and above

**Comment by arthuraltino** [comment]
Thanks!
